### ISSUE TITLE
fatal: Option -m cannot be combined with -c/-C/-F.

### ISSUE THREAD

**Issue by ExcitedSpider** [gha-utilities/workspace-commit#1]
**Describe the bug**

I got this following the intro in readme:

```
Error: Command failed: git commit -c "user.name gha-utilities" -c "user.email actions@github.com" commit -m "Updates externals" external/figma.common.json
fatal: Option -m cannot be combined with -c/-C/-F.
```

Detail logs can be found [here]( https://github.com/ExcitedSpider/adui-design-token/runs/1700038395?check_suite_focus=true#step:9:20)

**To Reproduce**

```yml
    - name: Add changes to Git tracking
      run: git add -A .
      
    - name: Commit changes
      uses: gha-utilities/workspace-commit@v0.0.3
      with:
        message: Updates externals
        all: true
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
```

**Expected behavior**

Successful commit.

**Screenshots**

![image](https://user-images.githubusercontent.com/35751871/104553064-f3b73f80-5674-11eb-8f45-932a54f5739f.png)

**fix**

Replace with: 
```
- name: config commit username
   run: git config user.name myusername
  
- name: config commit email
   run: git config user.email myemail
      
- name: Commit changes
   run: git commit -m "some message"
```
